version: "3.9"
services:
  main_service:
    build: ./main
    environment:
      PORT: 32206
      POSTGRES_URL: "postgresql+asyncpg://MASTER:MASTER@main_db:32402/MAIN_DB"
    ports:
      - "32206:32206"
    restart: unless-stopped
    depends_on:
      - main_db

  main_db:
    image: postgres
    environment:
      POSTGRES_USER: MASTER
      POSTGRES_PASSWORD: MASTER
      PGDATA: /data/postgres
      POSTGRES_DB: MAIN_DB
      PGPORT: 32402
    ports:
      - "32402:32402"
    restart: unless-stopped
    volumes:
      - main_db_data:/data/postgres

volumes:
  main_db_data:
